import { Property } from '@/types/property'

export const mockProperties: Property[] = [
  {
    id: '1',
    name: '万科金域华府',
    price: 520,
    pricePerSqm: 5.2,
    layout: '3室2厅2卫',
    area: 100,
    district: '朝阳区',
    floor: '15/28层',
    orientation: '南北通透',
    decoration: '精装修',
    age: 5,
    status: 'viewed',
    tags: ['采光好', '南北通透', '地铁近'],
    lastViewing: '2024-03-15',
    isFavorite: true,
    coverImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=450&fit=crop',
    viewingRecords: [
      {
        id: 'v1',
        date: '2024-03-15',
        visitNumber: 2,
        notes: '第二次看房，整体感觉不错，采光很好，客厅朝南，下午阳光充足。楼下有个小花园，环境安静。',
        photos: [
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=400&h=300&fit=crop',
        ],
      },
      {
        id: 'v2',
        date: '2024-03-01',
        visitNumber: 1,
        notes: '首次看房，整体印象良好。房东态度友好，房子保养得不错。',
        photos: [
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=400&h=300&fit=crop',
        ],
      },
    ],
    aiAnalysis: {
      pros: ['采光充足，南北通透', '小区环境优美，绿化率高', '距离地铁站步行5分钟', '房龄较新，物业管理规范'],
      cons: ['单价略高于周边均价', '主卧面积偏小', '停车位紧张'],
      suitableFor: ['改善型家庭', '有孩子的家庭', '注重通勤便利的上班族'],
      negotiationTips: ['可尝试以周边成交价为参考议价', '房东急售，有5-10万议价空间', '建议关注同小区其他房源对比'],
    },
    customFields: {},
  },
  {
    id: '2',
    name: '龙湖春江郦城',
    price: 380,
    pricePerSqm: 4.75,
    layout: '2室2厅1卫',
    area: 80,
    district: '海淀区',
    floor: '8/18层',
    orientation: '东南',
    decoration: '毛坯',
    age: 3,
    status: 'pending',
    tags: ['房东急售', '可议价', '学区房'],
    lastViewing: '',
    isFavorite: false,
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=450&fit=crop',
    viewingRecords: [],
    aiAnalysis: {
      pros: ['价格低于市场均价', '房龄新，设施完善', '对口优质学区'],
      cons: ['毛坯房需要装修投入', '朝向非正南', '楼层偏低'],
      suitableFor: ['首次置业刚需', '有学区需求的家庭', '投资客'],
      negotiationTips: ['房东急售，议价空间较大', '可争取10-15万优惠', '注意了解急售原因'],
    },
    customFields: {},
  },
  {
    id: '3',
    name: '绿地海珀云庭',
    price: 680,
    pricePerSqm: 5.67,
    layout: '4室2厅2卫',
    area: 120,
    district: '浦东新区',
    floor: '22/30层',
    orientation: '南',
    decoration: '豪装',
    age: 2,
    status: 'viewed',
    tags: ['豪装', '江景房', '品牌开发商'],
    lastViewing: '2024-03-10',
    isFavorite: true,
    coverImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=450&fit=crop',
    viewingRecords: [
      {
        id: 'v3',
        date: '2024-03-10',
        visitNumber: 1,
        notes: '高层江景视野很好，装修风格现代简约，家具家电齐全可直接入住。缺点是价格偏高。',
        photos: [
          'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=300&fit=crop',
          'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&h=300&fit=crop',
        ],
      },
    ],
    aiAnalysis: {
      pros: ['高层江景，视野开阔', '豪华装修，拎包入住', '品牌开发商，品质有保障', '小区配套完善'],
      cons: ['总价较高', '物业费偏高', '距离地铁站较远'],
      suitableFor: ['高端改善需求', '注重生活品质的家庭', '有车一族'],
      negotiationTips: ['高端房源议价空间有限', '可尝试争取车位或物业费优惠', '关注开发商促销活动'],
    },
    customFields: {},
  },
  {
    id: '4',
    name: '保利天悦',
    price: 450,
    pricePerSqm: 5.0,
    layout: '3室2厅1卫',
    area: 90,
    district: '天河区',
    floor: '12/25层',
    orientation: '西南',
    decoration: '简装',
    age: 8,
    status: 'sold',
    tags: ['已售', '地铁上盖'],
    lastViewing: '2024-02-20',
    isFavorite: false,
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=450&fit=crop',
    viewingRecords: [
      {
        id: 'v4',
        date: '2024-02-20',
        visitNumber: 1,
        notes: '地铁上盖位置非常好，但已经被其他买家签约了。',
        photos: [],
      },
    ],
    customFields: {},
  },
  {
    id: '5',
    name: '中海锦城',
    price: 320,
    pricePerSqm: 4.0,
    layout: '2室1厅1卫',
    area: 80,
    district: '南山区',
    floor: '6/20层',
    orientation: '北',
    decoration: '精装修',
    age: 10,
    status: 'pending',
    tags: ['低楼层', '噪音大', '价格便宜'],
    lastViewing: '',
    isFavorite: false,
    coverImage: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=450&fit=crop',
    viewingRecords: [],
    aiAnalysis: {
      pros: ['价格实惠，性价比高', '精装修省去装修成本', '小区成熟，配套完善'],
      cons: ['朝北采光差', '临街噪音较大', '房龄偏老'],
      suitableFor: ['预算有限的刚需', '过渡性居住', '出租投资'],
      negotiationTips: ['因朝向和噪音问题可大力议价', '预计有15-20万议价空间', '可要求业主承担部分税费'],
    },
    customFields: {},
  },
  {
    id: '6',
    name: '融创壹号院',
    price: 580,
    pricePerSqm: 5.27,
    layout: '3室2厅2卫',
    area: 110,
    district: '江北新区',
    floor: '18/32层',
    orientation: '南北通透',
    decoration: '精装修',
    age: 1,
    status: 'viewed',
    tags: ['次新房', '采光好', '户型方正'],
    lastViewing: '2024-03-12',
    isFavorite: true,
    coverImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=450&fit=crop',
    viewingRecords: [
      {
        id: 'v5',
        date: '2024-03-12',
        visitNumber: 1,
        notes: '房子很新，几乎没怎么住过。户型方正，得房率高。小区绿化很好，有儿童游乐设施。',
        photos: [
          'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400&h=300&fit=crop',
        ],
      },
    ],
    aiAnalysis: {
      pros: ['次新房，品质有保障', '户型方正，空间利用率高', '小区配套完善', '南北通透，通风采光好'],
      cons: ['新区配套仍在完善中', '距离市中心较远', '周边商业较少'],
      suitableFor: ['改善型需求', '有孩子的家庭', '看好新区发展的投资者'],
      negotiationTips: ['新房限售期刚过，业主可能急于变现', '可尝试议价8-12万', '关注同期房源挂牌价格'],
    },
    customFields: {},
  },
]
