-- Privacy-minimal first-party funnel analytics for the Hobby deployment.
-- Raw rows are not readable through the public API. Clients can only call the
-- validated insert function below; aggregate reporting stays in SQL Editor.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  event_name text not null check (
    event_name in (
      'activation_completed',
      'auth_mode_changed',
      'comparison_started',
      'landing_cta_clicked',
      'landing_demo_interacted',
      'landing_demo_opened',
      'landing_viewed',
      'property_added',
      'property_deleted',
      'property_milestone_reached',
      'property_mode_changed',
      'screenshot_batch_started',
      'screenshot_confirmed',
      'screenshot_parse_failed',
      'screenshot_parsed',
      'signin_failed',
      'signin_started',
      'signin_succeeded',
      'signup_failed',
      'signup_started',
      'signup_succeeded'
    )
  ),
  anonymous_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  pathname text not null default '/' check (char_length(pathname) <= 200),
  properties jsonb not null default '{}'::jsonb check (
    jsonb_typeof(properties) = 'object' and pg_column_size(properties) <= 4096
  ),
  utm_source text check (char_length(utm_source) <= 100),
  utm_medium text check (char_length(utm_medium) <= 100),
  utm_campaign text check (char_length(utm_campaign) <= 100),
  utm_content text check (char_length(utm_content) <= 100),
  created_at timestamptz not null default now()
);

create index if not exists idx_analytics_events_created_at
  on public.analytics_events(created_at desc);
create index if not exists idx_analytics_events_name_created_at
  on public.analytics_events(event_name, created_at desc);
create index if not exists idx_analytics_events_anonymous_created_at
  on public.analytics_events(anonymous_id, created_at desc);
create index if not exists idx_analytics_events_campaign_created_at
  on public.analytics_events(utm_campaign, created_at desc)
  where utm_campaign is not null;

alter table public.analytics_events enable row level security;
revoke all on table public.analytics_events from anon, authenticated;

create or replace function public.track_analytics_event(
  p_event_id uuid,
  p_event_name text,
  p_anonymous_id uuid,
  p_pathname text default '/',
  p_properties jsonb default '{}'::jsonb,
  p_utm_source text default null,
  p_utm_medium text default null,
  p_utm_campaign text default null,
  p_utm_content text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_event_id is null or p_anonymous_id is null then
    return;
  end if;

  if not p_event_name = any (array[
    'activation_completed',
    'auth_mode_changed',
    'comparison_started',
    'landing_cta_clicked',
    'landing_demo_interacted',
    'landing_demo_opened',
    'landing_viewed',
    'property_added',
    'property_deleted',
    'property_milestone_reached',
    'property_mode_changed',
    'screenshot_batch_started',
    'screenshot_confirmed',
    'screenshot_parse_failed',
    'screenshot_parsed',
    'signin_failed',
    'signin_started',
    'signin_succeeded',
    'signup_failed',
    'signup_started',
    'signup_succeeded'
  ]::text[]) then
    return;
  end if;

  if jsonb_typeof(coalesce(p_properties, '{}'::jsonb)) <> 'object'
    or pg_column_size(coalesce(p_properties, '{}'::jsonb)) > 4096 then
    return;
  end if;

  -- A single anonymous browser should never need more than this in an hour.
  if (
    select count(*)
    from public.analytics_events
    where anonymous_id = p_anonymous_id
      and created_at > now() - interval '1 hour'
  ) >= 120 then
    return;
  end if;

  insert into public.analytics_events (
    event_id,
    event_name,
    anonymous_id,
    user_id,
    pathname,
    properties,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_content
  ) values (
    p_event_id,
    p_event_name,
    p_anonymous_id,
    auth.uid(),
    left(coalesce(nullif(trim(p_pathname), ''), '/'), 200),
    coalesce(p_properties, '{}'::jsonb),
    nullif(left(trim(p_utm_source), 100), ''),
    nullif(left(trim(p_utm_medium), 100), ''),
    nullif(left(trim(p_utm_campaign), 100), ''),
    nullif(left(trim(p_utm_content), 100), '')
  )
  on conflict (event_id) do nothing;
end;
$$;

revoke all on function public.track_analytics_event(
  uuid, text, uuid, text, jsonb, text, text, text, text
) from public;
grant execute on function public.track_analytics_event(
  uuid, text, uuid, text, jsonb, text, text, text, text
) to anon, authenticated;
